### ISSUE TITLE
Interface 'InputProps' incorrectly extends interface 'FormControlBaseProps<string | number | readonly string[] | undefined>'

### ISSUE THREAD

**Issue by Torvaldi** [rsuite/rsuite#2119]
### What version of rsuite are you using?

5.2.0

### What version of React are you using?

17.0.2

### What browser are you using?

none

### Describe the Bug

I am using vite into my project, when I run dev server, everything works fine but when I try to build my application, the following error occurs:
```bash
$ tsc && vite build
node_modules/rsuite/esm/Input/Input.d.ts:6:18 - error TS2430: Interface 'InputProps' incorrectly extends interface 'FormControlBaseProps<string | number | readonly string[] | undefined>'.
  Types of property 'onChange' are incompatible.
    Type '((value: string, event: ChangeEvent<HTMLInputElement>) => void) | undefined' is not assignable to type '((value: string | number | readonly string[] | undefined, event: SyntheticEvent<Element, Event>) => void) | undefined'.
      Type '(value: string, event: ChangeEvent<HTMLInputElement>) => void' is not assignable to type '(value: string | number | readonly string[] | undefined, event: SyntheticEvent<Element, Event>) => void'.
        Types of parameters 'value' and 'value' are incompatible.
          Type 'string | number | readonly string[] | undefined' is not assignable to type 'string'.
            Type 'undefined' is not assignable to type 'string'.

6 export interface InputProps extends WithAsProps, Omit<React.InputHTMLAttributes<HTMLInputElement>, 'onChange' | 'size'>, FormControlBaseProps {
                   ~~~~~~~~~~


Found 1 error.

error Command failed with exit code 2.
```

Did I miss something?

### Expected Behavior

I should build my app correctly using vite.

### To Reproduce

You can check [this repo](https://github.com/Torvaldi/rsuite5-vite) to reproduce the error.

**Comment by SevenOutman** [comment]
Hi @Torvaldi , seems we need to fix the props type definitions.

As a workaround for now, you could use add `--skipLibCheck` flag to `tsc` command, or set `skipLibCheck: true` in your `tsconfig.json`.

**Comment by SevenOutman** [comment]
Fixed in v5.3.0

**Comment by iamgabrielsoft** [comment]
what version was this fixed, i still experience this error on v4.6.4


> Fixed in v5.3.0

**Comment by SevenOutman** [comment]
> what version was this fixed, i still experience this error on v4.6.4

This issue was found in version v5.2.0 and fixed in version v5.3.0. 

If you are using version 4.x and found similar issue, please try upgrading to newer 4.x versions and see if it's gone. If it's still there please open a new issue for it.

**Comment by iamgabrielsoft** [comment]
Yes to some extent...
I did solve the error by adding another params to the interface
