### ISSUE TITLE
Scrolling of overflow disabled Modal

### ISSUE THREAD

**Issue by george-of-314** [rsuite/rsuite#2172]
### What version of rsuite are you using?

4.9.3

### What version of React are you using?

17.0.1

### What browser are you using?

Mozilla

### Describe the Bug

When open large modal with overflow disabled I can scroll only using mouse scroll. Browser scrollbar or keyboard I cannot use
Why not?

### Expected Behavior

Scrolling using scrollbar and keyboard

**Comment by george-of-314** [comment]
Closed? And what should I do with this? How to fix bug locally?

**Comment by simonguo** [comment]
Hi @george-of-314,  fixed in [5.3.0](https://github.com/rsuite/rsuite/releases/tag/v5.3.0)

```
npm i rsuite@5.3.0
```

**Comment by george-of-314** [comment]
Using v4((

пн, 13 груд. 2021, 03:49 користувач Simon Guo ***@***.***>
пише:

**Comment by SevenOutman** [comment]
@george-of-314 Fixed in [v4.10.6](https://github.com/rsuite/rsuite/releases/tag/v4.10.6)

**Comment by george-of-314** [comment]
Still not working
npm list --depth=0 | grep rsuite@
├── rsuite@4.10.6


https://user-images.githubusercontent.com/9105235/146737182-fa6e99fc-e49d-4029-b0ea-55798c0d6a38.mp4

**Comment by simonguo** [comment]
@george-of-314  Please use the following examples to reproduce the problem you encountered.
https://codesandbox.io/s/busy-knuth-8w9jt

**Comment by george-of-314** [comment]
In this example scrollbar scrolling not working

**Comment by simonguo** [comment]
@george-of-314 

https://user-images.githubusercontent.com/1203827/146749552-3b2fd85c-3dc9-47fe-b2e5-7e2ac1bf5c21.mp4

**Comment by george-of-314** [comment]
Mozilla and Chrome @W10

https://youtu.be/Sv6-1BuQzvg
