### ISSUE TITLE
At switch am to pm or vice versa DateRangePicker auto selects the End Date

### ISSUE THREAD

**Issue by alive2020** [rsuite/rsuite#2839]
### What version of rsuite are you using?

"rsuite": "^5.19.1",

### What version of React are you using?

"react": "^18.2.0",

### What browser are you using?

Chrome

### Describe the Bug

When I attempt to change am to pm or pm to am, the DateRangePicker auto selects the end Date with whole month long.

![Screen Shot 2022-10-26 at 5 05 44 PM](https://user-images.githubusercontent.com/68528319/197970482-55491264-b2d2-44b9-addb-734a9a567690.png)

![Screen Shot 2022-10-26 at 5 06 00 PM](https://user-images.githubusercontent.com/68528319/197970524-a6de3295-5b03-4f2f-b00b-c9e77357c977.png)

https://user-images.githubusercontent.com/68528319/197971658-fa56fe53-bc44-4ad5-af88-d8282c605489.mov

https://user-images.githubusercontent.com/68528319/197971683-b50f43f4-8b7f-4d58-a195-624541396c5e.mov

### Expected Behavior

Change my EndDate time  from 04:50 AM to 04:50 **PM**, without resetting dates, as it did automatically from 11th of Oct to 14th of Oct to 11th of Oct to 11th of Nov

### To Reproduce

- Open DateRangePicker, 
- Select start and end dates, 
- Click to am/pm to switch.

https://codesandbox.io/s/stoic-sun-fgw8er

**Comment by alive2020** [comment]
Why you closed this bug report?  @SevenOutman  @simonguo 
The issue wasn't resolved!
I installed rsuite 5.21.0 and nothing has changed, I'm encountering the same problem as I described.

**Comment by simonguo** [comment]
The problem persists when the selected date range is within a month (ie when selected on a calendar).

**Comment by simonguo** [comment]
@alive2020  Fixed in [v5.22.0](https://github.com/rsuite/rsuite/releases/tag/v5.22.0)

**Comment by alive2020** [comment]
Hi @simonguo 
Thank you for the update, 
I'm happy that we have a progress,  but I checked with ver 5.22.0 and my problem wasn't solved yet.

I'm attaching the link to a screenshot video 
https://drive.google.com/file/d/1Yljqu-bYQ5vSdDx1xubY6oKNrkdsWXyq/view?usp=sharing

As you can see: if I set  the startDay and the endDay within the same month the time for startDay and the endDay autosets to 00:00:00 (it still uses the startDay time for endDay time) 

Only if I set the value of the startDay and the endDay - different months - the time applies properly. 
like below:
const [value, setValue] = React.useState([
    new Date("2017-02-01 00:00"),
    new Date("2017-03-02 23:59")
  ]);

And the defaultCalendarValue - doesn't really affect to default time preset.

As soon as I leave the preset  the startDay and the endDay range, and select dates from a different month like 
from March to April, the time autosets to 00:00:00, I think it uses the time of the startDay to the secondDay.

Could you please look at it?

And the am/pm meridian bug wasn't solved yet right ???

**Comment by simonguo** [comment]
Hi @alive2020   
Thanks for the video you recorded, let me find the cause of the bug.

**Comment by simonguo** [comment]
Hi @alive2020 
I re-fixed this after finding the cause of the problem. PR: https://github.com/rsuite/rsuite/pull/2884

https://codesandbox.io/s/exciting-voice-4qzltw
The above is an example that has been fixed. Please check to see if your problem has been solved. It will be released in the next version when it is confirmed to be correct.

**Comment by alive2020** [comment]
Hi @simonguo 
Thank you so much~
Just checked. The problem with time resetting was solved :) Thank you )))
Hope you would also gonna have time to look at the switch from am to pm or pm to am bug  
Video screen shots on top of this thread.

You can also reproduce on this example https://codesandbox.io/s/exciting-voice-4qzltw

**Comment by simonguo** [comment]
@alive2020  The issue where switching between AM and PM resulted in incorrect update of date ranges was just fixed as well  https://codesandbox.io/s/exciting-voice-4qzltw

**Comment by alive2020** [comment]
@simonguo  Do you mean that the AM/PM issue was fixed here https://codesandbox.io/s/exciting-voice-4qzltw ?

I just checked, it seems the issue still exists! no ?
You can check the screenshot video below

https://user-images.githubusercontent.com/68528319/201016111-93eb3d0d-50f3-4a39-a73b-7aafc09186b5.mov

**Comment by simonguo** [comment]
@alive2020  Sorry for the wrong link, it should be this https://codesandbox.io/s/vibrant-sun-cndxcl

**Comment by alive2020** [comment]
@simonguo Great. Works perfectly.
Thank you so much for the quick reply and for fixing everything.
Will be waiting for the release.

**Comment by simonguo** [comment]
Hi @alive2020  Released, fixed in 5.22.1
